USER_APP_OBJS =	output/userApp/main.o \
		output/userApp/shell.o \
		output/userApp/memTestCase.o \
		output/userApp/mytask.o \
		output/userApp/test_prio.o \
		output/userApp/test_RR.o \
		output/userApp/test_sjf.o
