include $(SRC_RT)/myOS/kernel/mem/Makefile
include $(SRC_RT)/myOS/kernel/task/Makefile
include $(SRC_RT)/myOS/kernel/scheduler/Makefile

KERNEL_OBJS = output/myOS/kernel/tick.o \
	      output/myOS/kernel/wallClock.o \
		  output/myOS/kernel/taskclock.o \
	      $(MEM_OBJS)\
		  $(TASK_OBJS)\
		  $(SCHEDULER_OBJS)\
